name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"
