name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  1-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"

  2-job:
    runs-on: ubuntu-latest
    needs: 1-job
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"
