name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  build_code:
    name: Build Code  # Pretty name
    runs-on: ubuntu-latest
    steps:
      - name: Build Code
        run: echo "Building the code..."

  code_analysis:
    name: Code Analysis
    needs: build_code
    runs-on: ubuntu-latest
    steps:
      - name: Code Analysis
        run: echo "Running code analysis..."

  unit_test:
    name: Unit Test
    needs: build_code
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        run: echo "Running unit tests..."

  build_push_snapshots:
    name: Build & Push Snapshots to Artifactory
    needs: [unit_test, code_analysis]  
    runs-on: ubuntu-latest
    steps:
      - name: Build & Push Snapshots to Artifactory
        run: echo "Building and pushing snapshots to Artifactory..."

  deploy_dev:
    name: Deploy to Dev
    needs: build_push_snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to development environment..."

  post_run_metric_dev:
    name: Post Run Metric Dev
    needs: deploy_dev
    runs-on: ubuntu-latest
    steps:
      - name: Post Run Metric Dev
        run: echo "Posting run metrics for dev..."

# Build Code
# Code Analysis
# Unit Test
# Build & Push snapshots to artifactory
# Deploy to uat
# Post run metric stage
# Create prod pre-release
# Create prod approval request
# Sending approval notification
# Prod approve
# Push prod to artifactory
# Deploy to prod
# Post run metric prod
# Create PR from release to main
# Rollback
# Post run metric rollback
