name: Template Workflow

on:
  workflow_dispatch:  # This triggers the workflow manually from GitHub UI
  push:
    branches:
      - feature/*
      - develop
      - release/*

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  call_pipeline:
    uses: phu-ng/cicd-scripts/.github/workflows/main.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
#    secrets: inherit