name: Template Workflow

on:
  workflow_dispatch:  # This triggers the workflow manually from GitHub UI
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  call_pipeline:
    uses: phu-ng/cicd-scripts/.github/workflows/main.yaml@main
